# Generated by Django 2.1.7 on 2019-08-24 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDproject', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('prior', models.CharField(choices=[('heigh', 'heigh'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=50)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('responsible_person', models.CharField(blank=True, max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Process', 'Process'), ('Finish', 'Finish'), ('Reject', 'Reject')], default='New', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
