# Generated by Django 2.1.7 on 2019-08-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name_task',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
