# Generated by Django 2.1.7 on 2019-08-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190824_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='IDproject',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
