# Generated by Django 2.1.7 on 2019-08-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190824_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ID_task',
            field=models.CharField(default='KH00001', max_length=100),
        ),
    ]
