# Generated by Django 2.1.7 on 2019-08-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_task_id_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ID_task',
            field=models.CharField(default='KH00001', max_length=100, unique=True),
        ),
    ]
