# Generated by Django 2.1.7 on 2019-08-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190827_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ID_task',
            field=models.CharField(default='KH00000', max_length=100, unique=True),
        ),
    ]
