# Generated by Django 2.1.7 on 2019-08-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190827_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ID_task',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
