# Generated by Django 2.1.7 on 2019-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190827_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Processing', 'Processing'), ('Finish', 'Finish'), ('Reject', 'Reject')], default='New', max_length=50),
        ),
    ]
