# Generated by Django 2.1.7 on 2019-09-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190903_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='muc_do_hoan_thanh',
            field=models.IntegerField(default=0),
        ),
    ]
