# Generated by Django 2.1.7 on 2019-09-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_task_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
    ]
